// Every Vietnamese string of the Accounts page lives here.
export const text = {
  title: 'Tài khoản',
  description: 'Tài khoản nhà cung cấp mà gateway xoay vòng và failover.',
  add: 'Thêm tài khoản',
  unknownError: 'Đã có lỗi xảy ra',
  retry: 'Thử lại',
  loading: 'Đang tải',
  loadFailed: 'Không tải được danh sách tài khoản',
  search: 'Tìm theo nhãn',
  searchPlaceholder: 'Tìm theo nhãn…',
  allProviders: 'Tất cả nhà cung cấp',
  providerFilter: 'Lọc theo nhà cung cấp',
  emptyTitle: 'Chưa có tài khoản nào',
  emptyHint:
    'Thêm tài khoản đầu tiên bằng khóa API hoặc đăng nhập OAuth để gateway bắt đầu nhận request.',
  noMatch: 'Không có tài khoản khớp bộ lọc',
  list: 'Danh sách tài khoản',
  col: {
    label: 'Nhãn',
    provider: 'Nhà cung cấp',
    status: 'Kiểm tra',
    active: 'Bật',
    actions: 'Thao tác',
  },
  standby: 'Dự phòng',
  customUrl: 'URL riêng',
  tested: {
    ok: (ms: number) => `Hoạt động · ${ms} ms`,
    bad: (ms: number) => `Lỗi · ${ms} ms`,
    none: 'Chưa kiểm tra',
  },
  on: (label: string) => `Bật ${label}`,
  standbyOf: (label: string) => `Đặt ${label} làm dự phòng`,
  actions: {
    test: (label: string) => `Kiểm tra ${label}`,
    models: (label: string) => `Xem model của ${label}`,
    rename: (label: string) => `Đổi nhãn ${label}`,
    remove: (label: string) => `Xóa ${label}`,
  },
  rename: {
    title: 'Đổi nhãn tài khoản',
    label: 'Nhãn',
    required: 'Nhập nhãn cho tài khoản.',
    save: 'Lưu',
  },
  remove: {
    title: 'Xóa tài khoản?',
    body: (label: string, provider: string) =>
      `Tài khoản "${label}" của ${provider} sẽ bị xóa cùng thông tin đăng nhập. Không thể hoàn tác.`,
    confirm: 'Xóa tài khoản',
    cancel: 'Hủy',
  },
  models: {
    title: (label: string) => `Model của ${label}`,
    empty: 'Nhà cung cấp không trả về model nào.',
    count: (n: number) => `${n} model`,
  },
  cancel: 'Hủy',
  close: 'Đóng',
  toast: {
    activeFailed: (why: string) => `Không đổi được trạng thái bật: ${why}`,
    renamed: 'Đã đổi nhãn',
    renameFailed: (why: string) => `Không đổi được nhãn: ${why}`,
    deleted: (label: string) => `Đã xóa tài khoản ${label}`,
    deleteFailed: (why: string) => `Không xóa được tài khoản: ${why}`,
    testOk: (label: string, ms: number) => `${label}: kiểm tra thành công (${ms} ms)`,
    testBad: (label: string, ms: number, why: string) =>
      `${label}: kiểm tra thất bại (${ms} ms)${why ? ` - ${why}` : ''}`,
    testFailed: (label: string, why: string) => `${label}: không kiểm tra được - ${why}`,
    added: 'Đã thêm tài khoản',
  },
  dialog: {
    title: 'Thêm tài khoản',
    pick: 'Chọn cách thêm tài khoản.',
    kinds: {
      api: { title: 'Khóa API', hint: 'Dán khóa API của nhà cung cấp.' },
      oauth: { title: 'Đăng nhập OAuth', hint: 'Đăng nhập trên trang của nhà cung cấp rồi dán mã.' },
      device: { title: 'Thiết bị', hint: 'Nhập mã hiển thị trên trang xác nhận của nhà cung cấp.' },
    },
    kindGroup: 'Kiểu tài khoản',
    next: 'Tiếp tục',
    back: 'Quay lại',
    provider: 'Nhà cung cấp',
    pickProvider: 'Chọn nhà cung cấp',
    noProviders: 'Không có nhà cung cấp nào cho kiểu này.',
    providersFailed: 'Không tải được danh sách nhà cung cấp.',
    custom: 'Nhà cung cấp tùy chỉnh',
    customId: 'Mã nhà cung cấp',
    customIdHint: 'Chữ thường, số hoặc dấu gạch ngang. Dùng làm tiền tố tên model.',
    customApi: 'Kiểu API',
    secret: 'Khóa API',
    secretRequired: 'Nhập khóa API.',
    accountId: 'Account ID',
    accountIdRequired: 'Nhập account ID.',
    baseUrl: 'Base URL',
    baseUrlOptional: 'Base URL (tùy chọn)',
    baseUrlRequired: 'Nhập base URL bắt đầu bằng http hoặc https.',
    label: 'Nhãn (tùy chọn)',
    noKey: 'Nhà cung cấp này không cần khóa.',
    submit: 'Thêm',
    submitting: 'Đang thêm',
    start: 'Bắt đầu đăng nhập',
    starting: 'Đang bắt đầu',
    open: 'Mở trang đăng nhập',
    openHint: 'Đăng nhập ở tab mới, sau đó dán URL chuyển hướng hoặc mã vào ô bên dưới.',
    paste: 'Dán URL hoặc mã',
    pasteRequired: 'Dán URL hoặc mã nhận được.',
    finish: 'Hoàn tất',
    finishing: 'Đang hoàn tất',
    deviceCode: 'Mã của bạn',
    deviceHint: 'Mở trang xác nhận và nhập mã này. Cửa sổ sẽ tự cập nhật khi bạn xác nhận xong.',
    deviceOpen: 'Mở trang xác nhận',
    waiting: 'Đang chờ bạn xác nhận…',
    expired: 'Mã đã hết hạn. Hãy bắt đầu lại.',
    restart: 'Bắt đầu lại',
  },
}
