// Every Vietnamese string of the API keys page.
export const s = {
  title: 'Khóa API',
  description:
    'Khóa API, giới hạn RPM, hạn dùng và danh sách model được phép. Chỉ quản lý được từ dashboard.',
  create: 'Tạo khóa',
  createFirst: 'Tạo khóa đầu tiên',
  retry: 'Thử lại',
  loading: 'Đang tải khóa API',
  loadFailed: 'Không tải được danh sách khóa',
  emptyTitle: 'Chưa có khóa API nào',
  emptyBody: 'Tạo khóa để cấp quyền gọi /v1 cho một máy hoặc một ứng dụng.',
  emptyFilter: 'Không có khóa nào khớp bộ lọc',
  filterLabel: 'Lọc theo trạng thái',
  filters: {
    all: 'Tất cả',
    active: 'Đang bật',
    disabled: 'Đã tắt',
    expired: 'Hết hạn',
  },
  status: { active: 'Đang bật', disabled: 'Đã tắt', expired: 'Hết hạn' },
  col: {
    name: 'Tên',
    key: 'Khóa',
    active: 'Bật',
    models: 'Model',
    expires: 'Hạn dùng',
    rpm: 'RPM',
    lastUsed: 'Lần dùng cuối',
    created: 'Ngày tạo',
    actions: 'Thao tác',
  },
  allModels: 'Mọi model',
  never: 'Không hết hạn',
  noRpm: 'Không giới hạn',
  unused: 'Chưa dùng',
  modelsCount: (n: number) => `${n} model`,
  tableLabel: 'Danh sách khóa API',

  toggleLabel: (name: string) => `Bật khóa ${name}`,
  toggleFailed: (name: string, why: string) =>
    `Không đổi được trạng thái khóa "${name}": ${why}`,
  usageLabel: (name: string) => `Lượng dùng khóa ${name}`,
  modelsLabel: (name: string) => `Sửa model khóa ${name}`,
  limitsLabel: (name: string) => `Giới hạn khóa ${name}`,
  revealLabel: (name: string) => `Xem khóa ${name}`,
  deleteLabel: (name: string) => `Xóa khóa ${name}`,

  createTitle: 'Tạo khóa API',
  createDesc: 'Khóa đầy đủ chỉ hiện một lần ngay sau khi tạo.',
  nameLabel: 'Tên khóa',
  namePlaceholder: 'Ví dụ: Máy build',
  nameHelp: 'Để trống thì dùng tên "key".',
  submitCreate: 'Tạo',
  creating: 'Đang tạo…',
  createFailed: 'Không tạo được khóa',
  cancel: 'Hủy',

  pickerLabel: 'Model được phép',
  pickerSearch: 'Tìm model',
  pickerHelpAll: 'Không chọn model nào nghĩa là khóa gọi được mọi model.',
  pickerSelected: (n: number) => `Đã chọn ${n} model`,
  pickerEmpty: 'Không có model khớp',
  pickerLoading: 'Đang tải danh sách model',
  pickerFailed: 'Không tải được danh sách model',
  pickerClear: 'Bỏ chọn hết',

  secretTitleNew: 'Khóa API mới',
  secretTitleReveal: 'Khóa API',
  secretDesc: (name: string) => `Khóa của "${name}".`,
  secretWarn:
    'Sao chép và lưu khóa này ngay. Sau khi đóng, khóa này không xem lại được từ thông báo này (chỉ xem lại được bằng thao tác "Xem khóa").',
  secretField: 'Khóa API',
  copy: 'Sao chép',
  copied: 'Đã sao chép khóa vào bộ nhớ tạm',
  copyFailed: 'Không sao chép được, hãy chọn và sao chép thủ công',
  savedConfirm: 'Tôi đã lưu khóa',
  close: 'Đóng',

  revealTitle: (name: string) => `Xem khóa "${name}"?`,
  revealBody:
    'Khóa đầy đủ sẽ hiện trên màn hình. Hãy chắc chắn không có ai nhìn thấy.',
  revealConfirm: 'Xem khóa',
  revealFailed: 'Không xem được khóa',

  modelsTitle: 'Model được phép',
  modelsDesc: (name: string) => `Chọn model khóa "${name}" được gọi.`,
  save: 'Lưu',
  saving: 'Đang lưu…',
  modelsSaved: 'Đã lưu danh sách model',
  modelsFailed: 'Không lưu được danh sách model',

  limitsTitle: 'Giới hạn khóa',
  limitsDesc: (name: string) => `Giới hạn tốc độ và hạn dùng của "${name}".`,
  rpmLabel: 'Số yêu cầu tối đa mỗi phút',
  rpmHelp: '0 nghĩa là không giới hạn.',
  rpmInvalid: 'RPM phải là số nguyên từ 0 đến 100000',
  expiresLabel: 'Hạn dùng',
  expiresHelp: 'Để trống nếu khóa không hết hạn. Giờ theo múi giờ của trình duyệt.',
  expiresPast: 'Hạn dùng phải ở tương lai',
  expiresInvalid: 'Hạn dùng không hợp lệ',
  expiresClear: 'Bỏ hạn dùng',
  limitsSaved: 'Đã lưu giới hạn',
  limitsFailed: 'Không lưu được giới hạn',

  deleteTitle: (name: string) => `Xóa khóa "${name}"?`,
  deleteBody:
    'Mọi máy đang dùng khóa này sẽ bị từ chối ngay. Không hoàn tác được.',
  deleteConfirm: 'Xóa',
  deleted: (name: string) => `Đã xóa khóa "${name}"`,
  deleteFailed: 'Không xóa được khóa',

  usageTitle: (name: string) => `Lượng dùng — ${name}`,
  usageDesc: '30 ngày gần nhất, theo ngày và model.',
  usageFailed: 'Không tải được lượng dùng',
  usageEmpty: 'Chưa có lượng dùng trong 30 ngày qua',
  usageEmptyBody: 'Số liệu sẽ hiện khi khóa này gọi /v1.',
  usageMinute: 'Phút vừa qua',
  usageRequests: 'Yêu cầu',
  usageInput: 'Token vào',
  usageOutput: 'Token ra',
  usageTotal: '30 ngày',
  usageChart: (n: number) => `Biểu đồ số yêu cầu theo ngày, ${n} ngày có dữ liệu`,
  usageCaption: 'Lượng dùng theo ngày và model',
  colDay: 'Ngày',
  colModel: 'Model',
}
